{
 "title": "Globaleda Room",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Dummy Device 1 - Park001", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Park001 Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(recvtime) as \"time\",\r\n  CAST(attrValue as decimal) as \"value\"\r\nFROM openiot.`urn_ngsi-ld_Device_001_Device`\r\nWHERE attrName = \"temperature\"\r\nORDER BY \"time\"  "
    }
   ]
  },
  {
   "title": "Park001 Humidity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(recvtime) as \"time\",\r\n  CAST(attrValue as decimal) as \"value\"\r\nFROM openiot.`urn_ngsi-ld_Device_001_Device`\r\nWHERE attrName = \"relativeHumidity\"\r\nORDER BY \"time\"  "
    }
   ]
  },
  { "title": "Dummy Device 2 - Park002", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Park002 Visitors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CAST(attrValue as decimal) as \"value\"\r\nFROM openiot.`urn_ngsi-ld_Device_002_Device`\r\nWHERE attrName = \"visitors\""
    }
   ]
  },
  {
   "title": "Park002 Wind Speed",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(recvtime) as \"time\",\r\n  CAST(attrValue as decimal) as \"value\"\r\nFROM openiot.`urn_ngsi-ld_Device_002_Device`\r\nWHERE attrName = \"windspeed\"\r\nORDER BY \"time\"  "
    }
   ]
  },
  { "title": "Globaleda Room", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CO2",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"device_frmpayload_data_bytes_co2_values_0\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"device_frmpayload_data_bytes_humidity_values_0\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"device_frmpayload_data_bytes_temperature_values_0\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}